"""add title_en and content_en to news

Revision ID: 78289f117ace
Revises: c539d8105bd7
Create Date: 2025-10-29 16:02:41.936027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78289f117ace'
down_revision = 'c539d8105bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('content_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
