"""add en fields to gallery

Revision ID: 7bcf7cc0e91d
Revises: 78289f117ace
Create Date: 2025-10-30 12:06:36.835185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcf7cc0e91d'
down_revision = '78289f117ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
