"""add english fields to top images

Revision ID: 86d1e323d5b1
Revises: ed7d3ece054b
Create Date: 2025-10-30 23:07:38.909868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d1e323d5b1'
down_revision = 'ed7d3ece054b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption_en', sa.String(length=255), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('caption_en')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_gallery_title_en')
        batch_op.drop_index('ix_gallery_title')
        batch_op.drop_index('ix_gallery_desc_en')
        batch_op.drop_index('ix_gallery_desc')

    # ### end Alembic commands ###
