"""Add news_id to TopImage

Revision ID: 8d67cb6a2d18
Revises: 
Create Date: 2025-05-15 13:08:23.167224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d67cb6a2d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.String(), nullable=True))
        batch_op.alter_column('news_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(
            'fk_top_image_news', 'news', ['news_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('news_title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###
