"""Add created_at to TopImage

Revision ID: c539d8105bd7
Revises: 8d67cb6a2d18
Create Date: 2025-05-16 15:01:12.723244

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'c539d8105bd7'
down_revision = '8d67cb6a2d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_image', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
